scope: __SCOPE__
name: __PATRONI_NAME__

restapi:
  listen: 0.0.0.0:8008
  connect_address: __PATRONI_NAME__:8008

etcd3:
  host: __ETCD_HOST__
  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: __MAX_CONNECTIONS__
        shared_buffers: __SHARED_BUFFERS__
        wal_level: replica
        hot_standby: on
        wal_keep_size: 1GB
        max_wal_senders: 10
        max_replication_slots: 10
        synchronous_commit: __SYNCHRONOUS_COMMIT__
        synchronous_standby_names: '__SYNCHRONOUS_STANDBY_NAMES__'

  initdb:
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - host replication replicator 0.0.0.0/0 md5
    - host all all 0.0.0.0/0 md5
    - local all all trust

  users:
    postgres:
      password: __POSTGRES_PASSWORD__
      options:
        - createrole
        - createdb
    replicator:
      password: __REPLICATION_PASSWORD__
      options:
        - replication

postgresql:
  listen: 0.0.0.0:5432
  connect_address: __PATRONI_NAME__:5432
  data_dir: /data/patroni
  bin_dir: /usr/lib/postgresql/15/bin
  authentication:
    replication:
      username: replicator
      password: __REPLICATION_PASSWORD__
    superuser:
      username: postgres
      password: __POSTGRES_PASSWORD__
  parameters:
    unix_socket_directories: '/var/run/postgresql'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
